{
 "title": "Git",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "GIT",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "<div class=\"text-center dashboard-header\">\n  <span>Overview Dashboard</span>\n</div>\n\n",
   "targets": [
    {
     "bucketAggs": [
      { "field": "metadata__timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "metadata__timestamp"
    }
   ]
  },
  {
   "title": "Commits",
   "type": "farski-blendstat-panel",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "grimoire_creation_date", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "grimoire_creation_date"
    }
   ]
  },
  {
   "title": "Files",
   "type": "farski-blendstat-panel",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 2 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "grimoire_creation_date", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "files",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "timeField": "grimoire_creation_date"
    }
   ]
  },
  {
   "title": "Authors",
   "type": "farski-blendstat-panel",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 2 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "metadata__timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "author_name",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "timeField": "metadata__timestamp"
    }
   ]
  },
  {
   "title": "Repositories",
   "type": "farski-blendstat-panel",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 2 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "metadata__timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "repo_name",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "timeField": "metadata__timestamp"
    }
   ]
  },
  {
   "title": "Projects",
   "type": "farski-blendstat-panel",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 2 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "metadata__timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "project",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "timeField": "metadata__timestamp"
    }
   ]
  },
  {
   "title": "Organization commits",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "author_org_name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      { "field": "metadata__timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "metadata__timestamp"
    }
   ]
  },
  {
   "title": "Authors activity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "Commits" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "Author_name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "grimoire_creation_date", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "grimoire_creation_date"
    }
   ]
  },
  {
   "title": "Authors",
   "type": "table",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 13 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "author_name",
       "id": "7",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "lines_changed",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "lines_added",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "lines_removed",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "files",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "project",
       "id": "8",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      },
      {
       "field": "hash",
       "id": "9",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "timeField": "metadata__timestamp"
    }
   ]
  },
  {
   "title": "Projects",
   "type": "table",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 13 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "project",
       "id": "2",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "hash",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      },
      {
       "field": "author_uuid",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      },
      {
       "field": "repo_name",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "timeField": "metadata__timestamp"
    }
   ]
  },
  {
   "title": "Commits",
   "type": "graph",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short", "label": "Commits" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "grimoire_creation_date", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "hash",
       "id": "1",
       "meta": {},
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "count"
      }
     ],
     "timeField": "grimoire_creation_date"
    }
   ]
  },
  {
   "title": "Commit heatmap",
   "type": "heatmap",
   "description": "Heatmap con frecuencia de commits, con frecuencia de refresco de 1h (eje Y).",
   "gridPos": { "h": 11, "w": 14, "x": 10, "y": 20 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "grimoire_creation_date",
       "id": "3",
       "settings": { "interval": "1h", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "hash",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "timeField": "grimoire_creation_date"
    }
   ]
  },
  {
   "title": "Commits",
   "type": "graph",
   "gridPos": { "h": 3, "w": 10, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "Commits" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "grimoire_creation_date", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "hash",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "timeField": "grimoire_creation_date"
    }
   ]
  },
  {
   "title": "Commits",
   "type": "graph",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short", "label": "Commits" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "grimoire_creation_date", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "hash",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "timeField": "grimoire_creation_date"
    }
   ]
  },
  {
   "title": "Organizations",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "author_org_name",
       "id": "2",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "hash",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      },
      {
       "field": "author_uuid",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      },
      {
       "field": "files",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "lines_added",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "lines_removed",
       "id": "6",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "project",
       "id": "7",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      },
      {
       "field": "repo_name",
       "id": "8",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      },
      {
       "field": "lines_changed",
       "id": "9",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "timeField": "metadata__timestamp"
    }
   ]
  },
  {
   "title": "Organizations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short", "label": "Commits" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "Author_org_name",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      { "field": "grimoire_creation_date", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tz",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "timeField": "grimoire_creation_date"
    }
   ]
  },
  {
   "title": "Repositories",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "repo_name",
       "id": "2",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "hash",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      },
      {
       "field": "author_uuid",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      },
      {
       "field": "author_org_name",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      },
      {
       "field": "lines_added",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "lines_removed",
       "id": "6",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "lines_changed",
       "id": "7",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "files",
       "id": "8",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "timeField": "commit_date"
    }
   ]
  },
  {
   "title": "Time Zone Commits (+/- UTC)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short", "label": "Commits" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "tz",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "metadata__timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "metadata__timestamp"
    }
   ]
  },
  {
   "title": "Lines Added vs Removed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "grimoire_creation_date", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "lines_added",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "timeField": "grimoire_creation_date"
    },
    {
     "bucketAggs": [
      {
       "field": "grimoire_creation_date",
       "id": "2",
       "settings": { "interval": "1d", "min_doc_count": 0, "offset": "", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "lines_removed",
       "id": "1",
       "inlineScript": "_value*-1",
       "meta": {},
       "settings": { "script": { "inline": "_value*-1" } },
       "type": "sum"
      }
     ],
     "timeField": "grimoire_creation_date"
    }
   ]
  }
 ]
}