{
 "title": "Mailing Lists",
 "time": { "from": "now-5y", "to": "now" },
 "panels": [
  {
   "title": "Emails",
   "type": "farski-blendstat-panel",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "grimoire_creation_date", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "timeField": "grimoire_creation_date"
    }
   ]
  },
  {
   "title": "Emails",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "grimoire_creation_date", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "grimoire_creation_date"
    }
   ]
  },
  {
   "title": "Email Senders",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "grimoire_creation_date", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "author_uuid",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "timeField": "grimoire_creation_date"
    }
   ]
  },
  {
   "title": "Email Senders",
   "type": "farski-blendstat-panel",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "metadata__timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "author_uuid",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "timeField": "metadata__timestamp"
    }
   ]
  },
  {
   "title": "Projects",
   "type": "table",
   "gridPos": { "h": 5, "w": 9, "x": 6, "y": 5 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "project",
       "id": "2",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" },
      {
       "field": "author_uuid",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "timeField": "grimoire_creation_date"
    }
   ]
  },
  {
   "title": "Time Zone Emails (+/- UTC)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "Emails" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "tz",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "metadata__timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "metadata__timestamp"
    }
   ]
  },
  {
   "title": "Mailing Lists",
   "type": "farski-blendstat-panel",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "metadata__timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "list",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "timeField": "metadata__timestamp"
    }
   ]
  },
  {
   "title": "Email Senders",
   "type": "table",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 10 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "author_name",
       "id": "2",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" },
      {
       "field": "project",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      },
      {
       "field": "list",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      },
      {
       "field": "size",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "timeField": "grimoire_creation_date"
    }
   ]
  },
  {
   "title": "Organization commits",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 10 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "author_org_name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      { "field": "metadata__timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "metadata__timestamp"
    }
   ]
  },
  {
   "title": "Mailing Lists",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "list",
       "id": "2",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" },
      {
       "field": "author_uuid",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      },
      {
       "field": "author_org_name",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "timeField": "metadata__timestamp"
    }
   ]
  }
 ]
}