{
 "title": "Plugins",
 "description": "Different Grafana plugins",
 "time": { "from": "now-5y", "to": "now" },
 "panels": [
  { "title": "Boom Theme", "type": "yesoreyeram-boomtheme-panel", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 3 },
   "content": "<h2>Clock</h2>\n\n",
   "targets": [
    {
     "bucketAggs": [
      { "field": "metadata__timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "metadata__timestamp"
    }
   ]
  },
  {
   "type": "grafana-clock-panel",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "metadata__timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "metadata__timestamp"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 10 },
   "content": "<h2>Polistat Panel</h2>\n\n",
   "targets": [
    {
     "bucketAggs": [
      { "field": "metadata__timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "metadata__timestamp"
    }
   ]
  },
  {
   "title": "Lines changed per organization",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 12 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "author_org_name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      { "field": "grimoire_creation_date", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "lines_changed",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "timeField": "grimoire_creation_date"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 21 },
   "content": "<h2>Radar Graph</h2>\n\n",
   "targets": [
    {
     "bucketAggs": [
      { "field": "metadata__timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "metadata__timestamp"
    }
   ]
  },
  {
   "title": "File extension in each project",
   "type": "snuids-radar-panel",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "file_ext",
       "id": "8",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "5" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "project",
       "id": "7",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "select metric",
       "id": "1",
       "meta": {},
       "pipelineAgg": "select metric",
       "pipelineVariables": [
        { "name": "var1", "pipelineAgg": "select metric" }
       ],
       "settings": {},
       "type": "count"
      }
     ],
     "timeField": "grimoire_creation_date"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 32 },
   "content": "<h2>Status Map</h2>\n\n",
   "targets": [
    {
     "bucketAggs": [
      { "field": "metadata__timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "metadata__timestamp"
    }
   ]
  },
  {
   "title": "Authors contribution",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "grimoire_creation_date", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "Author_uuid",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "timeField": "grimoire_creation_date"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 42 },
   "content": "<h2>Multistat</h2>\n\n",
   "targets": [
    {
     "bucketAggs": [
      { "field": "metadata__timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "metadata__timestamp"
    }
   ]
  },
  {
   "title": "Linnes added per organization",
   "type": "michaeldmoore-multistat-panel",
   "description": "Table-like panel with horizontal bars. Base limit in 50k linnes added. Blue (<50k) vs green (>50k). Lower limit 4k, high limit 1.77M.\n",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "author_org_name",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "lines_added",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "timeField": "grimoire_creation_date"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 52 },
   "content": "<h2>Diagram</h2>\n\n",
   "targets": [
    {
     "bucketAggs": [
      { "field": "metadata__timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "metadata__timestamp"
    }
   ]
  },
  {
   "title": "TFG Diagram",
   "type": "jdbranham-diagram-panel",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 54 },
   "format": "none",
   "valueName": "avg",
   "content": "graph LR\nA{SirMordred} -- Git/Github data --> B((ElasticS))\nA -- Git/Github data --> C((MariaDB))\nB --> D{Kibana}\nC --> D\nB --> E{Grafana}\nC -- Futura BD --> E",
   "targets": [
    {
     "bucketAggs": [
      { "field": "grimoire_creation_date", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "author_uuid",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "timeField": "grimoire_creation_date"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 61 },
   "content": "<h2>Blend stat (multiple query)</h2>\n\n",
   "targets": [
    {
     "bucketAggs": [
      { "field": "metadata__timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "metadata__timestamp"
    }
   ]
  },
  {
   "title": "Total lines added/changed/removed",
   "type": "farski-blendstat-panel",
   "gridPos": { "h": 4, "w": 13, "x": 0, "y": 63 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "grimoire_creation_date", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "lines_added",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "timeField": "grimoire_creation_date"
    },
    {
     "bucketAggs": [
      { "field": "grimoire_creation_date", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "lines_changed",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "timeField": "grimoire_creation_date"
    },
    {
     "bucketAggs": [
      { "field": "grimoire_creation_date", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "lines_removed",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "timeField": "grimoire_creation_date"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 67 },
   "content": "<h2>Pie Chart</h2>\n\n",
   "targets": [
    {
     "bucketAggs": [
      { "field": "metadata__timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "metadata__timestamp"
    }
   ]
  },
  {
   "title": "File extensions",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 69 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "file_ext",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "15" },
       "type": "terms"
      },
      { "field": "grimoire_creation_date", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "file_ext",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "timeField": "grimoire_creation_date"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 78 },
   "content": "<h2>Carpet Plot</h2>\n\n",
   "targets": [
    {
     "bucketAggs": [
      { "field": "metadata__timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "metadata__timestamp"
    }
   ]
  },
  {
   "title": "Commits heatmap",
   "type": "petrslavotinek-carpetplot-panel",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 80 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "grimoire_creation_date", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "grimoire_creation_date"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 91 },
   "content": "<h2>Annunciator</h2>\n\n",
   "targets": [
    {
     "bucketAggs": [
      { "field": "metadata__timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "metadata__timestamp"
    }
   ]
  },
  {
   "title": "Lines removed",
   "type": "michaeldmoore-annunciator-panel",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 93 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "grimoire_creation_date", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "lines_removed",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "timeField": "grimoire_creation_date"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 98 },
   "content": "<h2>Epict Panel</h2>\n\n",
   "targets": [
    {
     "bucketAggs": [
      { "field": "metadata__timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "metadata__timestamp"
    }
   ]
  },
  {
   "title": "Background Image",
   "type": "larona-epict-panel",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 100 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "grimoire_creation_date", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "files",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "timeField": "grimoire_creation_date"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 109 },
   "content": "<h2>Bubble Chart</h2>\n\n",
   "targets": [
    {
     "bucketAggs": [
      { "field": "metadata__timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "metadata__timestamp"
    }
   ]
  },
  {
   "title": "File extensions",
   "type": "digrich-bubblechart-panel",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 111 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "file_ext",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "grimoire_creation_date", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "file_ext",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "timeField": "grimoire_creation_date"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 121 },
   "content": "<h2>Datatable Panel</h2>\n\n",
   "targets": [
    {
     "bucketAggs": [
      { "field": "metadata__timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "metadata__timestamp"
    }
   ]
  },
  {
   "title": "Top Repositories",
   "type": "briangann-datatable-panel",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 123 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "repo_name",
       "id": "2",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "hash",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      },
      {
       "field": "author_uuid",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      },
      {
       "field": "author_org_name",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      },
      {
       "field": "lines_added",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "lines_removed",
       "id": "6",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "lines_changed",
       "id": "7",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "files",
       "id": "8",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "timeField": "commit_date"
    }
   ]
  }
 ]
}